# Generated by Django 3.1.7 on 2021-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
