# Generated by Django 3.1.7 on 2021-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
