# Generated by Django 3.1.7 on 2021-03-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_comment_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='reply',
        ),
    ]
