# Generated by Django 3.1.7 on 2021-03-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
