# Generated by Django 3.1.7 on 2021-03-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_comment_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(null=True),
        ),
    ]
