# Generated by Django 3.1.7 on 2021-03-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20210319_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_parent',
        ),
    ]
