# Generated by Django 3.1.7 on 2021-03-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210319_2237'),
        ('main_app', '0030_auto_20210320_0001'),
    ]

    operations = [
    ]
