# Generated by Django 3.1.7 on 2021-03-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_merge_20210320_2258'),
        ('main_app', '0031_merge_20210320_2259'),
    ]

    operations = [
    ]
