# Generated by Django 3.1.7 on 2021-03-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20210321_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='reply',
        ),
    ]
